# Generated by Django 3.2 on 2022-03-02 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=150, unique=True)),
                ('ncbi', models.IntegerField()),
                ('transcript', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenomeBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.CharField(max_length=2)),
                ('start', models.IntegerField()),
                ('ref', models.CharField(max_length=150)),
                ('alt', models.CharField(max_length=150)),
                ('hgvsc', models.CharField(max_length=150)),
                ('hgvsp', models.CharField(max_length=150)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ACMG', models.ManyToManyField(blank=True, to='vdb.ACMG')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vdb.genomebuild')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='var_created_by', to=settings.AUTH_USER_MODEL)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vdb.gene')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='var_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('build', 'chr', 'start', 'ref', 'alt'), name='unique_variant'),
        ),
    ]
