# Generated by Django 3.2 on 2022-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Benign'), (2, 'Likely benign'), (3, 'Variant of uncertain significance'), (4, 'Likely pathogenic'), (5, 'Pathogenic')], default=3),
        ),
    ]
