# Generated by Django 3.2 on 2022-03-04 10:50

import django.core.validators
from django.db import migrations, models
import vdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('vdb', '0002_alter_variant_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='alt',
            field=models.CharField(max_length=150, validators=[vdb.models.validate_capitalised, django.core.validators.RegexValidator('^[ACTGactg\\-]*$', 'Characters must be A, C, T, G or -')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='chr',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Input must contain only letters and numbers'), vdb.models.validate_capitalised]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hgvsc',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^c.[a-zA-Z0-9>_]*$', 'Invalid nomenclature - must follow HGVS nomenclature')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hgvsp',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^p.[(][a-zA-Z0-9>_*]*[)]$', 'Invalid nomenclature - must follow HGVS nomenclature')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='ref',
            field=models.CharField(max_length=150, validators=[vdb.models.validate_capitalised, django.core.validators.RegexValidator('^[ACTGactg\\-]*$', 'Characters must be A, C, T, G or -')]),
        ),
    ]
